[project]
name = "wallet-balance"
version = "1.0.0"
description = "examples"
readme = "README.rst"
requires-python = ">=3.11"
dependencies = [
    "steam",
]

[tool.uv.sources]
steam = { workspace = true }
